version: "3"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086" # InfluxDB HTTP API port
    environment:
      INFLUXDB_DB: k6 # The database name for k6 data
      INFLUXDB_ADMIN_USER: admin # InfluxDB admin username
      INFLUXDB_ADMIN_PASSWORD: admin # InfluxDB admin password

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana web interface
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin # Grafana admin password
    depends_on:
      - influxdb
